In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [4]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
d=np.array(([1,2,3],[4,7,9],[2,5,6]))
print(d)

[[1 2 3]
 [4 7 9]
 [2 5 6]]


In [6]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [7]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
import numpy as np
d=np.random.random((3,4))
print(d)

[[0.52447826 0.58996393 0.38292176 0.99655696]
 [0.70655274 0.8063126  0.89439907 0.30053185]
 [0.61581896 0.98291098 0.81702359 0.02175628]]


In [16]:
import numpy as np
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [11]:
import numpy as np
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 4)
12
int64
2


In [17]:
import numpy as np
c=np.zeros((1,2))
print(c)

[[0. 0.]]


In [ ]:
import numpy as np 
a=np.array([1,2,3,4,5])
print(a)